/* M.C.N. v4 final polish — bilingual carnet/passport/about links */
(function(){
  'use strict';
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const isEn=()=>localStorage.getItem('mcn-lang')==='en' || document.documentElement.classList.contains('is-english');
  const L={
    fr:{generated:'Carnet généré',date:'Date',score:'Score',taste:'À goûter',stay:'Où dormir',tip:'Conseil',maps:'Ouvrir Google Maps',pdf:'Télécharger le PDF',seal:'Ajouter le sceau',saved:'Sceau ajouté au passeport patrimoine.',empty:'Générez un carnet puis ajoutez un sceau.',copyOk:'Programme copié dans le presse-papiers.',notebookReady:'Carnet généré : votre programme complet est prêt.',passport:'Passeport patrimoine',passportCopy:'Les sceaux gagnés apparaissent ici après ajout depuis le carnet de route.',pdfTitle:'Carnet de Route Impérial',program:'Programme de visite',reco:'Recommandations personnalisées',mapsLabel:'Itinéraire réel Google Maps',footer:'Document généré localement par le prototype M.C.N. — aucune donnée personnelle transmise.'},
    en:{generated:'Generated notebook',date:'Date',score:'Score',taste:'To taste',stay:'Where to stay',tip:'Field tip',maps:'Open Google Maps',pdf:'Download PDF',seal:'Add seal',saved:'Seal added to the heritage passport.',empty:'Generate a notebook, then add a seal.',copyOk:'Program copied to the clipboard.',notebookReady:'Notebook generated: your full program is ready.',passport:'Heritage passport',passportCopy:'Earned seals appear here after you add them from the route notebook.',pdfTitle:'Imperial Route Notebook',program:'Visit program',reco:'Personalized recommendations',mapsLabel:'Real Google Maps route',footer:'Document generated locally by the M.C.N. prototype — no personal data transmitted.'}
  };
  const DATA={
    badaling:{name:'Badaling',dest:'Badaling Great Wall',tag:{fr:"La porte d’entrée iconique, fluide et accessible depuis Pékin.",en:'The iconic, smooth and accessible gateway from Beijing.'},copy:{fr:'Section restaurée, accès le plus simple depuis Pékin. Idéale pour familles, accessibilité et première découverte.',en:'Restored section with the easiest access from Beijing. Ideal for families, accessibility and a first discovery.'},title:{fr:'Badaling — Première grande traversée',en:'Badaling — First grand crossing'},food:{fr:'Zhajiangmian, jiaozi, thé au jasmin et snacks de Yanqing.',en:'Zhajiangmian, jiaozi, jasmine tea and Yanqing snacks.'},hotel:{fr:'Retour à Pékin conseillé ou hôtel confort à Yanqing.',en:'Return to Beijing recommended, or a comfort hotel in Yanqing.'},tip:{fr:'Arrivez avant 8h30 : lumière douce et files plus courtes.',en:'Arrive before 8:30 a.m.: soft light and shorter queues.'},timeline:{fr:['07:15|Départ depuis Pékin, marge de sécurité incluse.','09:00|Arrivée au centre d’accueil et récupération des billets.','09:30|Montée vers les tours nord avec pauses photo.','12:15|Déjeuner local et découverte des spécialités.','14:00|Musée / lecture patrimoniale sur la défense Ming.','16:00|Retour vers Pékin ou installation hôtel.'],en:['07:15|Departure from Beijing, safety margin included.','09:00|Arrival at the visitor center and ticket collection.','09:30|Climb toward the northern towers with photo stops.','12:15|Local lunch and discovery of regional specialties.','14:00|Museum / heritage reading on Ming defense.','16:00|Return to Beijing or hotel check-in.']}},
    mutianyu:{name:'Mutianyu',dest:'Mutianyu Great Wall',tag:{fr:'Le meilleur équilibre entre beauté, confort et panoramas.',en:'The best balance between beauty, comfort and panoramas.'},copy:{fr:'Panoramas plus calmes, section restaurée élégante, excellente pour photos et familles.',en:'Calmer panoramas, an elegant restored section, excellent for photos and families.'},title:{fr:'Mutianyu — Panorama premium et familial',en:'Mutianyu — Premium family panorama'},food:{fr:'Truite locale, nouilles, raviolis vapeur et thé vert.',en:'Local trout, noodles, steamed dumplings and green tea.'},hotel:{fr:'Boutique hôtel dans le district de Huairou ou retour Pékin.',en:'Boutique hotel in Huairou district or return to Beijing.'},tip:{fr:'Privilégiez la fin d’après-midi pour une lumière rasante spectaculaire.',en:'Choose late afternoon for spectacular low-angle light.'},timeline:{fr:['07:45|Départ depuis Pékin vers Huairou.','09:45|Arrivée à Mutianyu et montée téléphérique ou sentier doux.','10:30|Marche panoramique entre les tours 14 et 20.','12:45|Déjeuner local à Huairou.','14:30|Temps photo, descente et visite d’un village voisin.','17:00|Retour ou check-in boutique hôtel.'],en:['07:45|Departure from Beijing toward Huairou.','09:45|Arrival at Mutianyu and ascent by cable car or gentle path.','10:30|Panoramic walk between towers 14 and 20.','12:45|Local lunch in Huairou.','14:30|Photo time, descent and visit to a nearby village.','17:00|Return or boutique hotel check-in.']}},
    jinshanling:{name:'Jinshanling',dest:'Jinshanling Great Wall',tag:{fr:'La section des photographes et des marcheurs exigeants.',en:'The section for photographers and demanding walkers.'},copy:{fr:'Semi-restaurée, photogénique, parfaite pour ressentir la Muraille dans le paysage.',en:'Semi-restored, highly photogenic, perfect for feeling the Wall within the landscape.'},title:{fr:'Jinshanling — Traversée photographique',en:'Jinshanling — Photographic crossing'},food:{fr:'Plats paysans du Hebei, légumes de montagne, nouilles maison.',en:'Hebei countryside dishes, mountain vegetables and homemade noodles.'},hotel:{fr:'Guesthouse près de Gubeikou ou lodge panoramique.',en:'Guesthouse near Gubeikou or panoramic lodge.'},tip:{fr:'Chaussures de marche obligatoires : marches irrégulières et longues crêtes.',en:'Walking shoes required: uneven steps and long ridges.'},timeline:{fr:['06:30|Départ tôt pour profiter de la lumière du matin.','09:30|Arrivée et briefing sécurité.','10:00|Randonnée progressive sur les crêtes restaurées et sauvages.','12:30|Pique-nique ou déjeuner local.','14:00|Séquence photo Golden Wall et tours anciennes.','17:30|Retour ou nuit en guesthouse.'],en:['06:30|Early departure to enjoy morning light.','09:30|Arrival and safety briefing.','10:00|Progressive hike along restored and wild ridges.','12:30|Picnic or local lunch.','14:00|Golden Wall photo sequence and ancient towers.','17:30|Return or night in a guesthouse.']}},
    simatai:{name:'Simatai',dest:'Simatai Great Wall',tag:{fr:'L’expérience nocturne la plus spectaculaire.',en:'The most spectacular night experience.'},copy:{fr:'Section ouverte en soirée, atmosphère dramatique près de Gubei Water Town.',en:'Evening-access section with a dramatic atmosphere near Gubei Water Town.'},title:{fr:'Simatai — Muraille nocturne',en:'Simatai — Night Wall experience'},food:{fr:'Cuisine de Gubei Water Town, fondue locale, desserts chinois.',en:'Gubei Water Town cuisine, local hotpot and Chinese desserts.'},hotel:{fr:'Hôtel à Gubei Water Town pour prolonger l’expérience nocturne.',en:'Hotel in Gubei Water Town to extend the night experience.'},tip:{fr:'Réservez tôt : les créneaux de nuit sont limités et très demandés.',en:'Book early: night slots are limited and in high demand.'},timeline:{fr:['12:00|Départ tranquille depuis Pékin.','15:00|Arrivée à Gubei Water Town et promenade culturelle.','17:30|Dîner avant la montée.','19:00|Accès à Simatai illuminée.','20:30|Photos nocturnes et lecture du paysage.','22:00|Nuit sur place ou retour tardif.'],en:['12:00|Relaxed departure from Beijing.','15:00|Arrival at Gubei Water Town and cultural walk.','17:30|Dinner before the ascent.','19:00|Access to illuminated Simatai.','20:30|Night photos and landscape reading.','22:00|Stay overnight or late return.']}},
    jiankou:{name:'Jiankou',dest:'Jiankou Great Wall',tag:{fr:'Sauvage, intense, réservé aux profils expérimentés.',en:'Wild, intense, reserved for experienced visitors.'},copy:{fr:'Section non restaurée, spectaculaire mais exigeante. À aborder avec guide et prudence.',en:'Unrestored, spectacular but demanding. Approach with a guide and caution.'},title:{fr:'Jiankou — Expédition sauvage encadrée',en:'Jiankou — Guided wild expedition'},food:{fr:'Repas rural à Xizhazi, légumes sautés, tofu, thé chaud.',en:'Rural meal in Xizhazi, stir-fried vegetables, tofu and hot tea.'},hotel:{fr:'Maison d’hôtes locale simple ou retour tardif à Pékin.',en:'Simple local guesthouse or late return to Beijing.'},tip:{fr:'Ne partez pas seul : terrain instable, orientation difficile et préservation fragile.',en:'Do not go alone: unstable ground, difficult orientation and fragile preservation.'},timeline:{fr:['06:00|Départ avec guide spécialisé.','08:30|Briefing sécurité et accès village.','09:00|Montée progressive vers les tours sauvages autorisées.','12:00|Pause panoramique sans sortir des zones sûres.','14:00|Descente contrôlée et repas rural.','17:30|Retour vers Pékin.'],en:['06:00|Departure with a specialist guide.','08:30|Safety briefing and village access.','09:00|Progressive ascent toward authorized wild towers.','12:00|Panoramic break without leaving safe zones.','14:00|Controlled descent and rural meal.','17:30|Return to Beijing.']}},
    huanghuacheng:{name:'Huanghuacheng',dest:'Huanghuacheng Lakeside Great Wall',tag:{fr:'Muraille, eau et montagne dans une ambiance rare.',en:'Wall, water and mountains in a rare atmosphere.'},copy:{fr:'Section lacustre originale, idéale pour une visite calme et contemplative.',en:'Original lakeside section, ideal for a calm and contemplative visit.'},title:{fr:'Huanghuacheng — Muraille au bord de l’eau',en:'Huanghuacheng — Lakeside Great Wall'},food:{fr:'Poisson du lac, légumes sautés, nouilles et thé local.',en:'Lake fish, stir-fried vegetables, noodles and local tea.'},hotel:{fr:'Auberge lacustre ou hôtel confort à Huairou.',en:'Lakeside inn or comfort hotel in Huairou.'},tip:{fr:'Excellent choix au printemps et en automne pour les reflets sur le lac.',en:'Excellent choice in spring and autumn for lake reflections.'},timeline:{fr:['08:00|Départ depuis Pékin vers Huairou.','10:00|Arrivée au site lacustre.','10:30|Marche douce et points de vue sur l’eau.','12:30|Déjeuner poisson / spécialités locales.','14:30|Promenade photo ou bateau selon saison.','16:30|Retour vers Pékin.'],en:['08:00|Departure from Beijing toward Huairou.','10:00|Arrival at the lakeside site.','10:30|Gentle walk and viewpoints over the water.','12:30|Fish lunch / local specialties.','14:30|Photo walk or boat depending on season.','16:30|Return to Beijing.']}}
  };
  const keys=Object.keys(DATA);
  const tr=(obj)=>obj[isEn()?'en':'fr'];
  function toast(msg){ if(window.mcnToast) return window.mcnToast(msg); let t=$('.smart-toast'); if(!t){t=document.createElement('div');t.className='smart-toast';document.body.appendChild(t)} t.textContent=msg;t.classList.add('is-visible');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('is-visible'),2500); }
  function activeKey(){return $('.journey-pin.active')?.dataset.section || $('.atlas-site.is-active')?.dataset.section || 'badaling'}
  function scoreFor(key){return ({badaling:[72,96,82,48],mutianyu:[78,90,92,70],jinshanling:[92,58,98,86],simatai:[84,64,95,76],jiankou:[98,34,96,90],huanghuacheng:[86,72,92,82]}[key]||[72,96,82,48]);}
  function route(key=activeKey()){
    const d=DATA[key]||DATA.badaling, lang=isEn()?'en':'fr';
    const scores=scoreFor(key); let score=Math.round(scores.reduce((a,b)=>a+b,0)/4);
    const date=$('#visit-date')?.value || (lang==='en'?'free date':'date libre');
    const mode=$('#visit-transport')?.value==='car'?'driving':($('#visit-transport')?.value==='hike'?'walking':'transit');
    const maps=`https://www.google.com/maps/dir/?api=1&origin=Beijing&destination=${encodeURIComponent(d.dest)}&travelmode=${mode}`;
    return {key,name:d.name,title:tr(d.title),tag:tr(d.tag),copy:tr(d.copy),food:tr(d.food),hotelText:tr(d.hotel),tip:tr(d.tip),timeline:d.timeline[lang].map(x=>x.replace('|',' — ')),timelineRaw:d.timeline[lang],date,score,scores,maps};
  }
  function render(key=activeKey()){
    const r=route(key); $$('.journey-pin').forEach(p=>p.classList.toggle('active',p.dataset.section===key));
    if($('#selected-section-name')) $('#selected-section-name').textContent=r.name;
    if($('#selected-section-tagline')) $('#selected-section-tagline').textContent=r.tag;
    if($('#route-title')) $('#route-title').textContent=r.title;
    if($('#experience-score')) $('#experience-score').textContent=r.score;
    $('.experience-score')?.style.setProperty('--score',r.score);
    ['auth','access','photo','crowd'].forEach((id,i)=>{const m=$('#score-'+id); if(m)m.value=r.scores[i];});
    const tl=$('#route-timeline'); if(tl) tl.innerHTML=r.timelineRaw.map(x=>{const [time,text]=x.split('|');return `<li><time>${time}</time><span>${text}</span></li>`}).join('');
    if($('#food-reco')) $('#food-reco').textContent=r.food;
    if($('#hotel-reco')) $('#hotel-reco').textContent=r.hotelText;
    if($('#pro-tip')) $('#pro-tip').textContent=r.tip;
    if($('#maps-link')) $('#maps-link').href=r.maps;
    if($('#atlas-copy')) $('#atlas-copy').textContent=r.copy;
    localStorage.setItem('mcn-last-route',JSON.stringify(r));
    renderPassport();
    return r;
  }
  function renderPassport(){
    const earned=JSON.parse(localStorage.getItem('mcn-passport-stamps')||'[]');
    const html=keys.map(k=>`<button type="button" class="stamp ${earned.includes(k)?'is-earned':''}" data-stamp="${k}">${DATA[k].name}</button>`).join('') + (earned.length?'':`<p class="passport-empty">${L[isEn()?'en':'fr'].empty}</p>`);
    $$('.stamp-row,.passport-stamps-live').forEach(row=>{row.innerHTML=html;});
    const preview=$('.section-passport-preview');
    if(preview){ preview.classList.toggle('has-earned', earned.includes(activeKey())); preview.dataset.earnedCount=String(earned.length); }
  }
  function addSeal(key=activeKey()){
    let earned=JSON.parse(localStorage.getItem('mcn-passport-stamps')||'[]');
    if(!earned.includes(key)) earned.push(key);
    localStorage.setItem('mcn-passport-stamps',JSON.stringify(earned));
    renderPassport(); toast(L[isEn()?'en':'fr'].saved);
  }
  function openCarnet(){
    const r=render(), lang=isEn()?'en':'fr', t=L[lang];
    let m=$('.journey-carnet-modal'); if(!m){m=document.createElement('div');m.className='journey-carnet-modal';document.body.appendChild(m);}
    m.innerHTML=`<div class="journey-carnet-card"><button class="close-carnet" aria-label="Close">×</button><span class="eyebrow">${t.generated}</span><h2>${r.name}</h2><div class="carnet-paper"><h3>${r.title}</h3><p><strong>${t.date} :</strong> ${r.date} · <strong>${t.score} :</strong> ${r.score}/100</p><ol>${r.timeline.map(x=>`<li>${x}</li>`).join('')}</ol><div class="carnet-grid"><div><strong>${t.taste}</strong><span>${r.food}</span></div><div><strong>${t.stay}</strong><span>${r.hotelText}</span></div><div><strong>${t.tip}</strong><span>${r.tip}</span></div></div></div><div class="route-actions"><a class="imperial-btn" target="_blank" rel="noopener" href="${r.maps}">${t.maps}</a><button class="imperial-btn secondary mcn-v4-pdf" type="button">${t.pdf}</button><button class="imperial-btn secondary mcn-v4-add-seal" type="button">${t.seal}</button></div></div>`;
    m.classList.add('is-open');
    m.onclick=e=>{ if(e.target===m || e.target.closest('.close-carnet')) m.classList.remove('is-open'); if(e.target.closest('.mcn-v4-add-seal')) addSeal(r.key); if(e.target.closest('.mcn-v4-pdf')) makePdf(r); };
    toast(t.notebookReady);
  }
  function clean(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘]/g,"'").replace(/[“”]/g,'"').replace(/[–—]/g,' - ').replace(/[^\x20-\x7E]/g,'');}
  function esc(v){return clean(v).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
  function wrap(v,max){const w=clean(v).split(/\s+/).filter(Boolean), out=[]; let line=''; w.forEach(x=>{if((line+' '+x).trim().length>max){if(line)out.push(line); line=x;}else line=(line+' '+x).trim();}); if(line)out.push(line); return out;}
  function makePdf(r=route()){
    const lang=isEn()?'en':'fr', t=L[lang], W=595,H=842,ops=[],cmd=s=>ops.push(s),rect=(x,y,w,h,c)=>cmd(`${c} rg ${x} ${y} ${w} ${h} re f`),stroke=(x,y,w,h,c)=>cmd(`${c} RG ${x} ${y} ${w} ${h} re S`);
    const draw=(x,y,size,str,font='F1',color='0.11 0.10 0.09')=>cmd(`${color} rg BT /${font} ${size} Tf ${x} ${y} Td (${esc(str)}) Tj ET`);
    rect(0,0,W,H,'0.985 0.970 0.940'); rect(0,H-112,W,112,'0.20 0.08 0.04'); rect(0,H-8,W,8,'0.88 0.55 0.10');
    draw(44,H-38,10,'M.C.N. - UNESCO PROTOTYPE','F1','0.95 0.66 0.18'); draw(44,H-72,29,t.pdfTitle,'F2','1 0.90 0.72'); draw(44,H-96,12,`${r.name}  -  ${r.date}  -  ${t.score} ${r.score}/100`,'F1','0.95 0.66 0.18');
    let y=H-150; draw(44,y,22,r.title,'F2','0.22 0.08 0.03'); y-=24; rect(44,y,507,2,'0.88 0.55 0.10'); y-=32; draw(44,y,16,t.program,'F2','0.22 0.08 0.03'); y-=18;
    r.timeline.slice(0,7).forEach(line=>{const parts=line.split(' — '), time=parts.shift()||'', body=parts.join(' - '); rect(44,y-24,76,34,'0.88 0.55 0.10'); draw(62,y-4,11,time,'F2','1 1 1'); wrap(body,70).slice(0,2).forEach((l,i)=>draw(136,y-2-i*13,10.5,l)); y-=48;});
    y-=6; draw(44,y,16,t.reco,'F2','0.22 0.08 0.03'); y-=22; let x=44; [[t.taste,r.food],[t.stay,r.hotelText],[t.tip,r.tip]].forEach(([h,b])=>{rect(x,y-122,158,112,'1 0.985 0.955'); stroke(x,y-122,158,112,'0.74 0.46 0.12'); draw(x+12,y-32,12,h,'F2','0.22 0.08 0.03'); wrap(b,28).slice(0,6).forEach((l,i)=>draw(x+12,y-52-i*11,8.6,l)); x+=176;});
    y-=154; rect(44,y-58,507,58,'0.96 0.91 0.82'); draw(58,y-20,11,t.mapsLabel,'F2','0.22 0.08 0.03'); wrap(r.maps,92).slice(0,2).forEach((l,i)=>draw(58,y-38-i*11,8.2,l)); draw(44,36,8,t.footer,'F1','0.33 0.30 0.26');
    const stream=ops.join('\n'), objs=[]; objs.push('1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj'); objs.push('2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj'); objs.push('3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >> endobj'); objs.push('4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj'); objs.push('5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Times-Bold >> endobj'); objs.push(`6 0 obj << /Length ${stream.length} >> stream\n${stream}\nendstream endobj`);
    let pdf='%PDF-1.4\n',xref=[0]; objs.forEach(o=>{xref.push(pdf.length); pdf+=o+'\n'}); const start=pdf.length; pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+xref.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')+`\ntrailer << /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;
    const blob=new Blob([pdf],{type:'application/pdf'}), a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`carnet-${clean(r.name).toLowerCase().replace(/\s+/g,'-')}-${lang}.pdf`; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000);
  }
  function replaceInteractiveButtons(){
    ['generate-journey','save-passport','download-route-pdf-main','copy-route'].forEach(id=>{const old=$('#'+id); if(old && !old.dataset.v4){const n=old.cloneNode(true); n.dataset.v4='1'; if(id==='download-route-pdf-main'){n.id='download-route-pdf-main-v4'; n.removeAttribute('data-clean-pdf'); n.classList.remove('download-route-pdf-clean');} old.replaceWith(n);}});
    $('#generate-journey')?.addEventListener('click',e=>{e.preventDefault(); openCarnet();},true);
    $('#save-passport')?.addEventListener('click',e=>{e.preventDefault(); render(); addSeal(activeKey());},true);
    $('#download-route-pdf-main-v4')?.addEventListener('click',e=>{e.preventDefault(); e.stopImmediatePropagation(); makePdf(render());},true);
    $('#copy-route')?.addEventListener('click',async e=>{e.preventDefault(); const r=render(); try{await navigator.clipboard.writeText(`${r.title} — ${r.score}/100\n${r.timeline.join('\n')}`);}catch(_){} toast(L[isEn()?'en':'fr'].copyOk);},true);
  }
  function fixAbout(){
    const title=$('#team-title'); if(title && !title.dataset.v4fixed){title.dataset.v4fixed='1'; title.innerHTML='<span class="lang-fr"><span class="team-title-accent">4 profils</span> <span class="team-title-white">complémentaires</span></span><span class="lang-en"><span class="team-title-accent">4 profiles</span><br><span class="team-title-white">complementary</span></span>';}
  }
  function init(){
    fixAbout(); replaceInteractiveButtons(); render(activeKey()); renderPassport();
    $$('.journey-pin').forEach(p=>{ if(!p.dataset.v4click){p.dataset.v4click='1'; p.addEventListener('click',()=>setTimeout(()=>render(p.dataset.section),30)); }});
    document.addEventListener('click',e=>{ if(e.target.closest('[data-command="open-passport"]')) setTimeout(()=>{const m=$('.heritage-passport-modal'); if(m){$('.passport-modal-card h2',m) && ($('.passport-modal-card h2',m).textContent=L[isEn()?'en':'fr'].passport); const p=$('.passport-modal-card p',m); if(p)p.textContent=L[isEn()?'en':'fr'].passportCopy; renderPassport();}},80); },true);
    document.addEventListener('click',e=>{ if(e.target.closest('.lang-btn')) setTimeout(()=>{fixAbout(); render(activeKey()); renderPassport();},80); },true);
    document.addEventListener('change',e=>{ if(e.target.closest('.journey-form')) setTimeout(()=>render(activeKey()),30); },true);
  }
  /* v4 neutralisé en v10 : passeport, carnet, PDF et clonage de boutons sont gérés par mcn_v10.js + main.js. Fichier conservé pour compatibilité HTML. */
})();
